[build]
  command = "npm run build"
  publish = "dist/premium-node16/browser"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/premium-node16/server/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
